version: 2
jobs:
  node:
    working_directory: ~/react-native-radar
    docker:
      - image: circleci/node:8
    steps:
      - checkout
    
      - restore_cache:
          name: Restore node modules cache
          key: lock-v1-{{ checksum "package-lock.json" }}-{{ arch }}

      - run: npm install 

      - save_cache:
          name: Save node modules cache
          key: lock-v1-{{ checksum "package-lock.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: jest tests
          command: npm run testJs

      - persist_to_workspace:
          root: ~/react-native-radar
          paths:
            - node_modules

  android:
    working_directory: ~/react-native-radar
    docker:
      - image: circleci/android:api-28-node8-alpha
    steps:
      - checkout:

      - attach_workspace:
          at: ~/react-native-radar
      
      - run: npm run testAndroid

  ios:
    macos: 
      xcode: "10.1.0"
    working_directory: ~/react-native-radar
    
    steps:
      - checkout

      - restore_cache:
          name: Restore node modules cache
          key: lock-v1-{{ checksum "package-lock.json" }}-{{ arch }}

      - run: npm install
 
      - save_cache:
          name: Save node modules cache
          key: lock-v1-{{ checksum "package-lock.json" }}-{{ arch }}
          paths:
            - node_modules

      - restore_cache:
          name: Restore brew cache
          key: brew-cache-v1

      - run: brew update
      - run: brew upgrade
      - run: brew install carthage
      - run:
          command: carthage bootstrap
          working_directory: ios
      
      - save_cache:
          name: Save homebrew cache
          key: brew-cache-v1
          paths:
            - /usr/local/Homebrew

      - run: npm run testIOS

workflows:
  version: 2
  node-android-ios:
    jobs:
      - node
      - android:
          requires:
            - node
      - ios:
          requires:
            - node
